language: cpp
script: make
services:
    - docker
before_install:
    - docker build -t formorer/debian-indexer .

script: 
    - docker run -t formorer/debian-indexer ls -la
    - docker run -t formorer/debian-indexer make
